import Head from "next/head";
import Hero from "../Components/Hero/Hero";
import Layout from "../Components/Layout/Layout";

export default function Home() {
  return (
      <Layout>
        <Head>
          <title>FUDO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        
        <main>
        <Hero/>      
        </main>
      </Layout>
  );
}

